# Generated by Django 6.0 on 2026-01-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsem', to='dashboard.semester'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semester'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
